include:
  - board: xiao_ble/nrf52840/zmk
    shield: corcell_r
    artifact-name: Corcell_R-dya-studio-xiao_ble_zmk
    snippet: corcell-right-slot1-paw3222 studio-rpc-usb-uart
  - board: xiao_ble/nrf52840/zmk
    shield: corcell_l
    artifact-name: Corcell_L-dya-studio-xiao_ble_zmk
    snippet: corcell-left-slot1-paw3222
  - board: xiao_ble/nrf52840/zmk
    shield: settings_reset
    artifact-name: settings_reset-dya-studio-xiao_ble_zmk
