CONFIG_I2C=y
CONFIG_INPUT_IQS9151=n
CONFIG_PAW3222=n
CONFIG_CORCELL_A2_RDY_PROBE=y
CONFIG_CORCELL_A2_DIAGNOSTIC_INFO=n
CONFIG_ZMK_STUDIO_TRANSPORT_UART=n
CONFIG_LOG=y
CONFIG_LOG_BUFFER_SIZE=32768
CONFIG_LOG_PROCESS_THREAD_STARTUP_DELAY_MS=8000
