manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    - name: nykxx
      url-base: https://github.com/nykxx
  projects:
    - name: zmk-driver-azoteq-iqs5xx
      remote: nykxx
      revision: 27321f0232b50f0af31eb27ff97d539933467ea4
    - name: zmk
      remote: zmkfirmware
      revision: 354cff9
      import: app/west.yml
  self:
    path: config
